- action:
  - data:
      entity_id: counter.motion_counter
    service: counter.increment
  alias: Motion counter
  condition: []
  id: '1517643989583'
  trigger:
  - entity_id: sensor.motion
    platform: state
- action:
  - data:
      message: '{{states.sensor.new_image.state}}'
    service: notify.pushbullet
  alias: New image notification
  condition: []
  id: '1517653449704'
  trigger:
  - entity_id: sensor.new_image
    platform: state
- action:
  - data:
      entity_id: counter.motion_counter
    service: counter.reset
  alias: Daily reset motion counter
  condition: []
  id: '1517730530569'
  trigger:
  - at: 00:00:00
    platform: time
