- id: '1513346519354'
  alias: House_idle
  trigger:
  - entity_id: binary_sensor.motion_at_home
    for:
      minutes: 5
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: input_boolean.house_idle
    service: input_boolean.turn_on
- id: '1513520328271'
  alias: House_motion
  trigger:
  - entity_id: binary_sensor.motion_at_home
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: input_boolean.house_idle
    service: input_boolean.turn_off
- action:
  - data:
      entity_id: timer.kettle
    service: timer.start
  alias: Kettle on timer
  condition: []
  id: '1518374196815'
  trigger:
  - entity_id: binary_sensor.kettle
    platform: state
    to: 'on'
- action:
  - service: shell_command.overwrite_motion_image
  alias: Overwrite MOTION
  condition: []
  id: '1517653449704'
  trigger:
  - entity_id: camera.last_captured_motion
    platform: state
- action:
  - data:
      entity_id: counter.motion_counter
    service: counter.increment
  alias: Motion counter
  condition: []
  id: '1517643989583'
  trigger:
  - entity_id: sensor.motion
    platform: state
- action:
  - data:
      entity_id: counter.motion_counter
    service: counter.reset
  alias: Daily reset motion counter
  condition: []
  id: '1517730530569'
  trigger:
  - at: 00:00:00
    platform: time
- action:
  - data:
      message: Created {{trigger.event.data.file}} in {{trigger.event.data.folder}}
    data_template:
      message: Created {{trigger.event.data.file}} in {{trigger.event.data.folder}}
    service: notify.pushbullet
  alias: New file alert
  condition: []
  id: '1520092824697'
  trigger:
  - event_data:
      event_type: created
    event_type: folder_watcher
    platform: event
