## HASS config
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 39
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/
    - /share

frontend:
  javascript_version: es5
discovery:
  ignore:
    - apple_tv
    - belkin_wemo
    - philips_hue
    - plex_mediaserver
history:
logbook:
sun:
config:
hassio:
#cloud:
ios:
python_script:
updater:
  include_used_components: true
#logger:
#  default: debug

camera:
  - platform: local_file
    file_path: /share/motion/latest.jpg
    name: "Live view"
  - platform: local_file
    file_path: /share/motion/dummy.jpg
    name: "dummy"

counter:
  motion_counter:
    initial: 0
    step: 1

folder_watcher:
  - folder: /share/motion
    patterns:
      - '*capture.jpg'

http:
  api_password: !secret http_password
  login_attempts_threshold: 5

image_processing:
  - platform: classificationbox
    ip_address: 192.168.0.18
    port: 8080
    confidence: 50
    scan_interval: 1000
    source:
      - entity_id: camera.dummy

mqtt:
  broker: !secret nas_ip

notify:
  - name: robins_and_marias_iphones
    platform: group
    services:
      - service: ios_robins_iphone
      - service: ios_marias_iphone
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat_id


###########################################################################
## Includes

script: !include scripts.yaml
switch: !include switch.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
automation: !include automations.yaml
group: !include groups.yaml
