homeassistant:
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  customize: !include customize.yaml

frontend:
config:
updater:
discovery:
history:
logbook:
map:
cloud:
speedtestdotnet:
mobile_app:
lovelace:
  mode: yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: info

blink:
  username: !secret blink_username
  password: !secret blink_password

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

mqtt:
  discovery: true
  broker: localhost
  port: 1883
  username: robin
  password: !secret mqtt_password

camera:
  - platform: onvif
    host: !secret dericam_ip
    name: dericam_1_onvif
    password: !secret dericam_1_password
    

sensor:
  - platform: london_underground
    line:
      - Jubilee
  - platform: uk_transport
    app_id: !secret transport_api_ID
    app_key: !secret transport_api_ID_Key
    queries:
      - mode: train
        origin: MOT
        destination: WAT

panel_iframe:
  ssh:
    title: SSH
    icon: mdi:wrench
    url: http://hassio.local:7681
  logs:
    title: Logs
    icon: mdi:wrench
    url: http://hassio.local:4277
  ide:
    title: IDE
    icon: mdi:code-braces
    url: http://hassio.local:8321
  glances:
    title: Glances
    icon: mdi:speedometer
    url: http://hassio.local:61208
  signalbox:
    title: Signalbox
    icon: mdi:speedometer
    url: https://www.map.signalbox.io/

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: 39
    unit_system: metric
    time_zone: Europe/London
    radius: 1000
