## HASS config
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 39
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/
    - /share

frontend:
  javascript_version: es5
discovery:
  ignore:
    - plex_mediaserver
    - apple_tv
history:
logbook:
sun:
config:
hassio:
#cloud:
ios:
python_script:
updater:
  include_used_components: true
#logger:
#  default: debug

###########################################################################
## Zones
zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 200
  icon: mdi:home


zone 1:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 1000
  icon: mdi:worker

zone 3:
  name: Waterloo
  latitude: 51.5032
  longitude: -0.1123
  radius: 200
  icon: mdi:train
###########################################################################

blink:
  username: !secret blink_username
  password: !secret blink_password

camera:
  - platform: local_file
    file_path: /share/motion/latest.jpg
    name: "Live view"
  - platform: local_file
    file_path: /share/motion/MOTION.jpg
    name: "Last captured motion"

counter:
  motion_counter:
    initial: 0
    step: 1

hue:
  bridges:
    - host: 192.168.0.3

http:
  api_password: !secret http_password
  login_attempts_threshold: 5

input_boolean:
  house_idle:
    name: No motion for at least 5 minutes
    initial: off
    icon: mdi:timer
  elgato_door:
    name: Elgato door sensor
    icon: mdi:door

ifttt:
  key: !secret ifttt_key

light:
  platform: hue
  host: !secret hue_ip

mqtt:
  broker: !secret nas_ip

notify:
  - name: robins_and_marias_iphones
    platform: group
    services:
      - service: ios_robins_iphone
      - service: ios_marias_iphone
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

#recorder:
#  db_url: !secret my_sql_nas
recorder:
  db_url: !secret google_sql

timer:
  kettle:
    duration: '00:05:00'

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat_id

shell_command:
  overwrite_motion_image: 'cp -rf {{states.sensor.new_image.state}} /share/motion/MOTION.jpg'

wemo:
  static:
    - !secret wemo_ip

###########################################################################
## Includes

script: !include scripts.yaml
switch: !include switch.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
automation: !include automations.yaml
group: !include groups.yaml
