homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.0
  longitude: -0.0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /share

frontend:
config:
hassio:
http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
updater:
# Discover some devices automatically
#discovery:
conversation:
history:
logbook:
map:
sun:

camera:
  - platform: local_file
    file_path: /share/motion/latest.jpg
    name: "Live view"
  - platform: local_file
    file_path: /share/motion/MOTION.jpg
    name: "Last captured motion"

counter:
  motion_counter:
    initial: 0
    step: 1

input_boolean:
  elgato_door:
    name: Elgato door sensor
    icon: mdi:door

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

sensor:
  - platform: folder
    folder: /share/motion/
    filter: '*motion-capture.jpg'
  - platform: command_line
    scan_interval: 20
    name: new_image
    command: "ls /share/motion -Art | tail -n -3 | grep 'capture.jpg'"
  - platform: template
    sensors:
      number_of_files_motion:
        friendly_name: "Motion images"
        value_template: "{{states.sensor.motion.attributes.number_of_files}}"

shell_command:
  overwrite_motion_image: 'cp -rf {{states.sensor.last_captured_image.state}} /share/motion/MOTION.jpg'

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat_id

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
