- platform: folder
  folder: /share/motion/
  filter: '*motion-capture.jpg'
- platform: command_line
  scan_interval: 20
  name: new_image
  command: "ls /share/motion -Art | tail -n -3 | grep 'capture.jpg'"
#- platform: hue

- platform: history_stats
  name: Time in bed
  entity_id: binary_sensor.in_bed_bayesian
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24

- platform: london_underground
  line:
    - District

- platform: min_max
  type: mean
  name: Mean temperature
  entity_ids:
    - sensor.blink_blink_camera_percy_temperature
    - sensor.living_room_temperature
    - sensor.bedroom_temperature
    - sensor.hall_temperature

#- platform: uk_transport
#  app_id: !secret uk_transport_app_id
 # app_key: !secret uk_transport_app_key
 # queries:
 #   - mode: train
 #     origin: MAL
 #     destination: WIM

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'

- platform: google_travel_time
  name: Home to work
  api_key: !secret google_api
  origin: zone.Home
  destination: zone.Work

- platform: google_travel_time
  name: Work to home
  api_key: !secret google_api
  origin: zone.Work
  destination: zone.Home

- platform: google_travel_time
  name: Home to Waterloo
  api_key: !secret google_api
  origin: zone.Home
  destination: zone.Waterloo
  options:
    mode: transit

#- platform: darksky
 # api_key: !secret darksky_api
  #name: darksky_sensor
 # monitored_conditions:
  #  - temperature
  #  - precip_probability
  #  - summary

- platform: speedtest
  monitored_conditions:
    - download

# Trains
- platform: template
  sensors:
    time_in_bed_template:
      friendly_name: 'Time in bed'
      value_template: '{{states.sensor.time_in_bed.attributes.value}}'
    bayes_probability:
      friendly_name: 'Bayes probability'
      value_template: '{{states.binary_sensor.in_bed_bayesian.attributes.probability}}'
    next_train_status:
      friendly_name: 'Next train status'
      value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].status}}'
    next_train_estimated:
      friendly_name: 'Next train estimated'
      value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].estimated}}'
    next_train_scheduled:
      friendly_name: 'Next train scheduled'
      value_template: '{{states.sensor.next_train_to_wim.attributes.next_trains[0].scheduled}}'
    next_train_in:
      friendly_name: 'Next train in'
      value_template: '{{states.sensor.next_train_to_wim.state}}'
    merton_pm10:
      friendly_name: 'Merton PM10'
      value_template: '{{states.sensor.merton.attributes.data[0].pollutants[0].summary}}'
    living_room_temperature:
      friendly_name: 'Living room temperature'
      value_template: '{{states.sensor.living_room_motion_sensor.attributes.temperature}}'
      unit_of_measurement: °C
    living_room_light_level:
      friendly_name: 'Living room light level'
      value_template: '{{states.sensor.living_room_motion_sensor.attributes.lux}}'
      unit_of_measurement: lux
    bedroom_temperature:
      friendly_name: 'Bedroom temperature'
      value_template: '{{states.sensor.bedroom_motion_sensor.attributes.temperature}}'
      unit_of_measurement: °C
    hall_temperature:
      friendly_name: 'Hall temperature'
      value_template: '{{states.sensor.hall_motion_sensor.attributes.temperature}}'
      unit_of_measurement: °C
    wemo_current_power_w:
      friendly_name: 'Wemo current power'
      value_template: '{{float(states.switch.wemo_insight.attributes.current_power_w)}}'
      unit_of_measurement: W
    wemo_today_energy_kwh:
      friendly_name: 'Wemo today energy'
      value_template: '{{float(states.switch.wemo_insight.attributes.today_energy_kwh)}}'
      unit_of_measurement: Kwh
    number_of_files_motion:
      friendly_name: "Motion images"
      value_template: "{{states.sensor.motion.attributes.number_of_files}}"
