- platform: folder
  folder: /share/motion/
  filter: '*motion-capture.jpg'

- platform: template
  sensors:
    last_added_file:
      friendly_name: Last added file
      value_template: "{{states.camera.dummy.attributes.file_path}}"
    number_of_files_motion:
      friendly_name: "Motion images"
      value_template: "{{states.sensor.motion.attributes.number_of_files}}"
